# -*- coding: utf-8 -*-
"""POO_266_2024-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xUAWBQfD61oLKJ2xmpjHwrOp2H_eOrl5
"""

class mochila:
    #atributos
    marca_modelo=None
    cor=None
    volume_max=None
    volume_atual=0
    estado='fechada'
    peso_max=None
    peso_atual=0
    comprimento_alça_dir=0
    comprimento_alça_esq=0
    comprimento_max_alça_direita=None
    comprimento_max_alça_esquerda=None

    #métodos

    def abrir(self):
      if self.estado=='aberta':
        print('A mochila já se encontra aberta!')
      else:
         self.estado='aberta'
         print(f'estado atual da mochila:{self.estado}')

    def fechar(self):
      if self.estado=='fechada':
        print('A mochila já se encontra fechada!')
      else:
         self.estado='fechada'
         print(f'estado atual da mochila:{self.estado}')




    def colocar_objeto(self,volume,peso):
      if self.estado=='aberta':
        if self.volume_atual+volume <= self.volume_max and self.peso_atual+peso <= self.peso_max:
          self.volume_atual+=volume
          self.peso_atual+=peso
          print('Objeto adicionado com sucesso!')
        else:
          print('O objeto não cabe na mochila!')
      else:
        print('Primeiro tem que abrir a mochila!')

    def retirar_objeto(self,volume,peso):
        if self.estado=='aberta':
           if self.volume_atual>0 and self.peso_atual>0:
              self.volume_atual-=volume
              self.peso_atual-=peso
           else:
              print('A mochila já está vazia!')
        else:
          print('Primeiro abra a mochila!')

    def ajustar_alça_eaquerda(self,valor):
      pass

    def ajustar_alça_direita(self,valor):
      pass

# =============================== objetos ================================
m1 = mochila()
# caracterizar o objeto
m1.marca_modelo = "Dell"
m1.cor='preto'
m1.volume_max = 20
m1.peso_max = 10
m1.comprimento_max_alça_direita=20
m1.comprimento_max_alça_esquerda=20

# testar os comportamentos

# abrindo a mochila
m1.abrir()
# testando os comportamentos (métodos)
m1.colocar_objeto(3,6)
m1.colocar_objeto(4,3)
m1.colocar_objeto(5,7)
m1.retirar_objeto(3,6)
m1.colocar_objeto(5,7)
m1.fechar()